"""
Cxapp/app/license.py
======================
Cxapp-only license/trial tracker — NOT the Sapp.License model. Sapp's
License is associate-issued and platform-wide; Cxapp owners self-signup
with no associate involvement, so they get their own lightweight trial
clock tied 1:1 to CxOwnerProfile.

Rule: 7-day trial from signup. After expiry, every Cxapp view except
company profile and the plan-purchase page redirects to plan purchase.
Enforced in Cxapp/middleware.py — this module only holds the model,
the plan choices, pricing, and the purchase views.

PRICING MODEL
-------------
Per-employee-per-month (PEPM), billed annually, with a monthly floor
per tier so small companies (<20 employees) don't pay a near-zero bill
that doesn't cover hosting. Floors are set against realistic Render
baseline infra cost (~$80/mo = ~₹6,650/mo for app + Postgres +
workspace) so a handful of paying customers actually cover hosting,
not just look market-competitive. GST is 18% flat (SaaS is an
intangible service — no HSN/SAC ambiguity, code 997331).

Enterprise has no self-serve PEPM rate; it's contact-sales, priced
per negotiation. The floor listed is a display anchor only.
"""

from decimal import Decimal, ROUND_HALF_UP
from datetime import timedelta

from django.db import models
from django.utils import timezone
from django import forms
from django.contrib import messages
from django.shortcuts import render, redirect

TRIAL_DAYS = 7
GST_RATE = Decimal('0.18')

PLAN_CHOICES = [
    ('trial',      'Trial'),
    ('basic',      'Basic'),
    ('premium',    'Premium'),
    ('enterprise', 'Enterprise'),
]

PLAN_DURATIONS_DAYS = {
    'basic': 365,
    'premium': 365 * 3,
    'enterprise': 365 * 10,
}

# ₹ per employee per month, excl. GST. Enterprise has no self-serve
# PEPM — pricing is negotiated, so it's omitted from calculate_price's
# auto-quote path and shown as "Contact Sales" in the template.
PLAN_PEPM = {
    'basic': Decimal('49'),
    'premium': Decimal('89'),
}

# Minimum monthly bill per tier, excl. GST — the real price for any
# company under ~20-40 employees, since PEPM alone wouldn't cover
# hosting at that scale. Enterprise floor is a display anchor only.
PLAN_FLOOR = {
    'basic': Decimal('1999'),
    'premium': Decimal('2999'),
    'enterprise': Decimal('9999'),
}

PLAN_YEARS = {
    'basic': 1,
    'premium': 3,
    'enterprise': 10,
}


def calculate_price(plan_code, employee_count):
    """
    Returns a dict with the full price breakdown for one year of the
    given plan at the given employee count:
        {
            'monthly_pepm_total': Decimal,   # pepm * employee_count, pre-floor
            'monthly_billed':     Decimal,   # max(pepm total, floor) — what they actually pay/mo
            'months':             int,       # plan duration in months
            'subtotal':           Decimal,   # monthly_billed * months, excl. GST
            'gst':                Decimal,   # 18% of subtotal
            'total':              Decimal,   # subtotal + gst
        }
    Enterprise returns floor-only figures (no PEPM math) since it's a
    contact-sales tier — the numbers shown are indicative, not a quote.
    """
    if plan_code not in PLAN_FLOOR:
        raise ValueError(f'Unknown plan: {plan_code}')

    employee_count = max(0, int(employee_count or 0))
    floor = PLAN_FLOOR[plan_code]
    pepm = PLAN_PEPM.get(plan_code)  # None for enterprise

    pepm_total = (pepm * employee_count) if pepm is not None else Decimal('0')
    monthly_billed = max(pepm_total, floor)

    months = PLAN_YEARS[plan_code] * 12
    subtotal = (monthly_billed * months).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)
    gst = (subtotal * GST_RATE).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)
    total = subtotal + gst

    return {
        'monthly_pepm_total': pepm_total.quantize(Decimal('0.01'), rounding=ROUND_HALF_UP),
        'monthly_billed': monthly_billed.quantize(Decimal('0.01'), rounding=ROUND_HALF_UP),
        'months': months,
        'subtotal': subtotal,
        'gst': gst,
        'total': total,
    }


class CxPlan(models.Model):
    """
    One row per CxOwnerProfile. Created automatically at signup with
    plan='trial' and a 7-day expiry. Purchasing a plan updates this
    same row rather than creating a new one — one active plan per owner.

    employee_count_at_purchase / amount_paid are a lightweight audit
    trail — the actual invoice of record should still be generated by
    whatever payment gateway integration handles the transaction.
    """
    owner        = models.OneToOneField('Cxapp.CxOwnerProfile', on_delete=models.CASCADE,
                                        related_name='plan')
    plan         = models.CharField(max_length=20, choices=PLAN_CHOICES, default='trial')
    started_at   = models.DateTimeField(auto_now_add=True)
    expires_at   = models.DateTimeField()
    is_active    = models.BooleanField(default=True)
    updated_at   = models.DateTimeField(auto_now=True)

    employee_count_at_purchase = models.PositiveIntegerField(null=True, blank=True)
    amount_paid_excl_gst       = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    gst_amount                 = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    amount_paid_incl_gst       = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)

    class Meta:
        app_label = 'Cxapp'
        db_table = 'cx_plan'
        verbose_name = 'Owner Plan'
        verbose_name_plural = 'Owner Plans'

    def __str__(self):
        return f'{self.owner.company.company_name} — {self.get_plan_display()} (expires {self.expires_at:%Y-%m-%d})'

    @classmethod
    def start_trial(cls, owner_profile):
        """Called once at Cxapp signup."""
        return cls.objects.create(
            owner=owner_profile,
            plan='trial',
            expires_at=timezone.now() + timedelta(days=TRIAL_DAYS),
        )

    def is_valid(self):
        return self.is_active and self.expires_at >= timezone.now()

    def days_remaining(self):
        delta = self.expires_at - timezone.now()
        return max(0, delta.days)

    def upgrade(self, plan_code, employee_count=None):
        """
        Owner purchases a plan. Extends from now, not from old expiry.
        Stores the priced-at employee count and computed amounts as an
        audit trail; recompute via calculate_price() if you need to
        re-quote rather than trusting these as the final invoice.
        """
        if plan_code not in PLAN_DURATIONS_DAYS:
            raise ValueError(f'Unknown plan: {plan_code}')

        if employee_count is None:
            employee_count = self.owner.employees.filter(is_deleted=False).count()

        pricing = calculate_price(plan_code, employee_count)

        self.plan = plan_code
        self.expires_at = timezone.now() + timedelta(days=PLAN_DURATIONS_DAYS[plan_code])
        self.is_active = True
        self.employee_count_at_purchase = employee_count
        self.amount_paid_excl_gst = pricing['subtotal']
        self.gst_amount = pricing['gst']
        self.amount_paid_incl_gst = pricing['total']
        self.save(update_fields=[
            'plan', 'expires_at', 'is_active', 'updated_at',
            'employee_count_at_purchase', 'amount_paid_excl_gst',
            'gst_amount', 'amount_paid_incl_gst',
        ])
        return pricing


# ── Views ────────────────────────────────────────────────────────────────────
# These two views are the ALWAYS-ALLOWED destinations — must never be
# blocked by the license middleware, or an expired owner could never
# reach the purchase page. See Cxapp/middleware.py ALWAYS_ALLOWED_NAMES.

def cxapp_plan_purchase(request):
    from Cxapp.views import cx_login_required

    @cx_login_required
    def _view(request):
        plan = getattr(request.cx_owner_profile, 'plan', None)
        employee_count = request.cx_owner_profile.employees.filter(is_deleted=False).count()

        if request.method == 'POST':
            chosen = request.POST.get('plan')
            if chosen not in PLAN_DURATIONS_DAYS:
                messages.error(request, 'Please select a valid plan.')
            elif chosen == 'enterprise':
                messages.info(request, 'Enterprise is a contact-sales tier — reach out to get a quote.')
            else:
                if plan is None:
                    plan = CxPlan.objects.create(
                        owner=request.cx_owner_profile, plan='trial',
                        expires_at=timezone.now(),
                    )
                pricing = plan.upgrade(chosen, employee_count=employee_count)
                messages.success(
                    request,
                    f"Plan upgraded to {plan.get_plan_display()}. "
                    f"Valid until {plan.expires_at:%d %b %Y}. "
                    f"Billed ₹{pricing['total']:,.2f} (incl. GST) for {employee_count} employee(s)."
                )
                return redirect('cxapp_dashboard')

        # Live price breakdown per tier, computed against the company's
        # actual current employee count — this is what the template renders.
        plan_pricing = []
        for code, label in PLAN_CHOICES:
            if code == 'trial':
                continue
            if code == 'enterprise':
                plan_pricing.append({
                    'code': code, 'label': label, 'contact_sales': True,
                    'floor': PLAN_FLOOR[code],
                })
                continue
            pricing = calculate_price(code, employee_count)
            plan_pricing.append({
                'code': code,
                'label': label,
                'contact_sales': False,
                'pepm': PLAN_PEPM[code],
                'floor': PLAN_FLOOR[code],
                'years': PLAN_YEARS[code],
                **pricing,
            })

        return render(request, 'Cxapp/plan_purchase.html', {
            'plan': plan,
            'employee_count': employee_count,
            'plan_pricing': plan_pricing,
            'gst_rate_pct': int(GST_RATE * 100),
        })

    return _view(request)
