# Generated by Django 6.0.1 on 2026-02-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
