# Generated by Django 6.0.1 on 2026-04-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aapp', '0003_alter_branch_branch_address_alter_branch_branch_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='driving_license_expiry',
            field=models.DateField(blank=True, db_column='Driving_License_Expiry', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='driving_license_name',
            field=models.CharField(blank=True, db_column='Driving_License_Name', max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='driving_license_number',
            field=models.CharField(blank=True, db_column='Driving_License_Number', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_expiry',
            field=models.DateField(blank=True, db_column='Passport_Expiry', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_name',
            field=models.CharField(blank=True, db_column='Passport_Name', max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_number',
            field=models.CharField(blank=True, db_column='Passport_Number', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='voterid',
            field=models.CharField(blank=True, db_column='VoterID', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='voterid_name',
            field=models.CharField(blank=True, db_column='VoterID_Name', max_length=200),
        ),
    ]
