# Generated by Django 6.0.1 on 2026-04-08 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aapp', '0005_alter_designation_unique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='Cotact_mobile',
            new_name='contact_mobile',
        ),
    ]
