# Generated by Django 6.0.1 on 2026-04-09 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aapp', '0006_rename_cotact_mobile_branch_contact_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('Contract', 'Contract'), ('Intern', 'Intern')], default='Permanent', max_length=20),
        ),
    ]
