# Generated by Django 6.0.1 on 2026-04-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aapp', '0007_employee_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='internship_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='intership_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
