# Generated by Django 6.0.1 on 2026-04-09 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aapp', '0008_employee_contract_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='intership_start_date',
            new_name='internship_start_date',
        ),
    ]
