# Generated by Django 6.0.1 on 2026-05-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aapp', '0010_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='salary_year',
            field=models.PositiveSmallIntegerField(choices=[(2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031)]),
        ),
    ]
