# Generated by Django 6.0.1 on 2026-06-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aapp', '0011_alter_attendance_salary_year'),
        ('Aapp', '0011_employee_leave'),
    ]

    operations = [
    ]
