# Generated by Django 6.0.1 on 2026-06-21 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aapp', '0012_merge_20260620_2115'),
        ('Sapp', '0006_company_created_at_company_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='ordinary_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='attendance',
            name='ot_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='attendance',
            name='ot_wages_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='employee_leave',
            name='encashmanent_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee_leave',
            name='leave_encased',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='employee_leave',
            name='leave_lapsed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='FactoryRegistration',
            fields=[
                ('factory_id', models.AutoField(primary_key=True, serialize=False)),
                ('factory_license_no', models.CharField(max_length=100, unique=True)),
                ('occupier_name', models.CharField(max_length=255)),
                ('manager_name', models.CharField(max_length=255)),
                ('factory_area_sqm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_hp_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_workers_day', models.IntegerField()),
                ('max_workers_night', models.IntegerField()),
                ('license_expiry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='Sapp.company')),
            ],
            options={
                'db_table': 'factory_registration',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FactoryAccidentRegister',
            fields=[
                ('accident_id', models.AutoField(primary_key=True, serialize=False)),
                ('accident_date', models.DateField()),
                ('nature_of_accident', models.CharField(max_length=255)),
                ('injury_description', models.TextField()),
                ('is_fatal', models.BooleanField(default=False)),
                ('days_lost', models.IntegerField(default=0)),
                ('reported_to_dish', models.BooleanField(default=False)),
                ('dish_reference_no', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factory_accidents', to='Aapp.employee')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to='Aapp.factoryregistration')),
            ],
            options={
                'db_table': 'factory_accident_register',
                'ordering': ['-accident_date'],
            },
        ),
        migrations.CreateModel(
            name='FactoryVesselExamination',
            fields=[
                ('vessel_id', models.AutoField(primary_key=True, serialize=False)),
                ('vessel_description', models.TextField()),
                ('exam_date', models.DateField()),
                ('examiner_name', models.CharField(max_length=255)),
                ('max_permissible_pressure', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_fit_for_use', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vessel_examinations', to='Aapp.factoryregistration')),
            ],
            options={
                'db_table': 'factory_vessel_examination',
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='FactoryWhitewashRegister',
            fields=[
                ('whitewash_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_description', models.TextField()),
                ('type_of_work', models.CharField(max_length=100)),
                ('date_done', models.DateField()),
                ('next_due_date', models.DateField()),
                ('contractor_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitewash_records', to='Aapp.factoryregistration')),
            ],
            options={
                'db_table': 'factory_whitewash_register',
                'ordering': ['-date_done'],
            },
        ),
        migrations.CreateModel(
            name='MinimumWagesOvertimeRegister',
            fields=[
                ('ot_register_id', models.AutoField(primary_key=True, serialize=False)),
                ('ot_date', models.DateField()),
                ('overtime_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ordinary_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ot_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ot_wages_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ot_details', to='Aapp.attendance')),
            ],
            options={
                'db_table': 'minimum_wages_overtime_register',
                'ordering': ['-ot_date'],
            },
        ),
        migrations.CreateModel(
            name='FactoryAnnualReturn',
            fields=[
                ('return_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('total_workers_male', models.IntegerField(default=0)),
                ('total_workers_female', models.IntegerField(default=0)),
                ('total_man_days', models.IntegerField(default=0)),
                ('total_overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_accidents', models.IntegerField(default=0)),
                ('total_wages_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('filing_status', models.CharField(choices=[('Draft', 'Draft'), ('Filed', 'Filed'), ('Acknowledged', 'Acknowledged')], default='Draft', max_length=50)),
                ('acknowledgement_no', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_returns', to='Aapp.factoryregistration')),
            ],
            options={
                'db_table': 'factory_annual_return',
                'ordering': ['-year'],
                'unique_together': {('factory', 'year')},
            },
        ),
        migrations.CreateModel(
            name='LeaveWithWagesRegister',
            fields=[
                ('leave_register_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('leave_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('leave_availed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('leave_lapsed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('leave_encashed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('encashment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_wages_records', to='Aapp.employee')),
            ],
            options={
                'db_table': 'leave_with_wages_register',
                'ordering': ['-year', 'employee'],
                'unique_together': {('employee', 'year')},
            },
        ),
    ]
