# Generated by Django 6.0.7 on 2026-07-24 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aapp', '0015_salary_processing_salary_structure_salary_slip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary_slip',
            name='salary_structure_id',
        ),
        migrations.RemoveField(
            model_name='salary_slip',
            name='absent_days',
        ),
        migrations.RemoveField(
            model_name='salary_slip',
            name='present_days',
        ),
        migrations.AddField(
            model_name='salary_slip',
            name='cca_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salary_slip',
            name='cycle_allowance_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salary_slip',
            name='da_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salary_slip',
            name='designation_id',
            field=models.ForeignKey(db_column='DesignationID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Aapp.designation'),
        ),
        migrations.AddField(
            model_name='salary_slip',
            name='labour_welfare_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salary_slip',
            name='labour_welfare_employer_contribution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salary_slip',
            name='lunch_allowance_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salary_slip',
            name='travel_allowance_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salary_slip',
            name='washing_allowance_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salary_slip',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='salary_slip',
            name='working_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='salary_structure',
        ),
    ]
