# Generated by Django 6.0.7 on 2026-07-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aapp', '0016_remove_salary_slip_salary_structure_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_leave',
            name='salary_year',
            field=models.PositiveSmallIntegerField(choices=[(2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031)]),
        ),
    ]
