# Generated by Django 6.0.7 on 2026-08-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aapp', '0020_drop_superseded_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='minimumwagesovertimeregister',
            name='ot_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='wages_deduction',
            name='salary_year',
            field=models.PositiveSmallIntegerField(choices=[(2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031)]),
        ),
        migrations.AlterField(
            model_name='wages_fine',
            name='salary_year',
            field=models.PositiveSmallIntegerField(choices=[(2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031)]),
        ),
    ]
