# Generated by Django 6.0.7 on 2026-08-11 16:00

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bank_name',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Bank Name',
                'verbose_name_plural': 'Bank Names',
                'db_table': 'sa_banks',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('Districtid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'db_table': 'sa_districts',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('Stateid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('state_code', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'db_table': 'sa_states',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('start_date', models.DateField()),
                ('shut_date', models.DateField(blank=True, null=True)),
                ('tagline1', models.CharField(blank=True, max_length=255, null=True)),
                ('address1', models.CharField(blank=True, max_length=155, null=True)),
                ('address2', models.CharField(blank=True, max_length=155, null=True)),
                ('address3', models.CharField(blank=True, max_length=155, null=True)),
                ('pin', models.CharField(blank=True, max_length=6, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('phone2', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile', models.CharField(max_length=10)),
                ('mobile2', models.CharField(blank=True, max_length=10, null=True)),
                ('email1', models.EmailField(max_length=254)),
                ('email2', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('pan', models.CharField(default='AAAAA0000A', max_length=10, unique=True)),
                ('tan', models.CharField(blank=True, max_length=10, null=True)),
                ('cin', models.CharField(blank=True, max_length=21, null=True)),
                ('account', models.CharField(blank=True, max_length=20, null=True)),
                ('ifsc', models.CharField(blank=True, max_length=11, null=True)),
                ('branch_address', models.CharField(blank=True, max_length=255, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('created_at', models.DateTimeField(default=datetime.date.today)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(default=datetime.date.today)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('letterhead_mode', models.CharField(choices=[('drawn', 'Generated header/footer (no physical letterhead)'), ('preprinted', 'Pre-printed stationery (blank margins only)'), ('overlay', 'Digital letterhead overlay (background PDF)')], default='drawn', help_text="How PDFs handle this company's letterhead.", max_length=15)),
                ('letterhead_top_margin_mm', models.PositiveSmallIntegerField(blank=True, help_text='Blank top margin (mm) to match pre-printed stationery. Only used when letterhead_mode is preprinted/overlay.', null=True)),
                ('letterhead_bottom_margin_mm', models.PositiveSmallIntegerField(blank=True, help_text='Blank bottom margin (mm) to match pre-printed stationery.', null=True)),
                ('letterhead_background_pdf', models.FileField(blank=True, help_text='PDF of the letterhead artwork — required when letterhead_mode is overlay.', null=True, upload_to='letterheads/')),
                ('bank_id', models.ForeignKey(blank=True, db_column='BankID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companybank', to='Sapp.bank_name')),
                ('district_id', models.ForeignKey(db_column='DistrictID', on_delete=django.db.models.deletion.CASCADE, related_name='companydistrict', to='Sapp.district')),
                ('state_id', models.ForeignKey(db_column='StateID', on_delete=django.db.models.deletion.CASCADE, related_name='companystate', to='Sapp.state')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'sa_Company',
            },
        ),
        migrations.CreateModel(
            name='associateuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associate_id', models.CharField(max_length=50, unique=True)),
                ('company_added_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspension_end_time', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='associate_profile', to=settings.AUTH_USER_MODEL)),
                ('companyid', models.ManyToManyField(blank=True, related_name='associate_company', to='Sapp.company')),
            ],
            options={
                'db_table': 'associate_users',
                'ordering': ['associate_id'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('license_id', models.AutoField(primary_key=True, serialize=False)),
                ('license_key', models.CharField(max_length=100, unique=True)),
                ('license_type', models.CharField(choices=[('trial', 'Trial'), ('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='trial', max_length=20)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=20)),
                ('max_users', models.PositiveIntegerField(default=5)),
                ('suspension_reason', models.TextField(blank=True, null=True)),
                ('revoke_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('associate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='Sapp.associateuser')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='Sapp.company')),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
                'db_table': 'sa_licenses',
                'ordering': ['-expiry_date'],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sapp.state'),
        ),
        migrations.CreateModel(
            name='SubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('operator', 'Operator'), ('employee', 'Employee')], default='employee', max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspension_end_time', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', models.TextField(blank=True, null=True)),
                ('associate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_users', to='Sapp.associateuser')),
                ('companyid', models.ManyToManyField(blank=True, related_name='subuser_company', to='Sapp.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subuser_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sub User',
                'verbose_name_plural': 'Sub Users',
                'db_table': 'sa_sub_users',
                'ordering': ['associate__associate_id', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_activity_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('owner', 'Owner'), ('associate', 'Associate'), ('operator', 'Operator'), ('employee', 'Employee')], default='associate', max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspension_end_time', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='company_statury',
            fields=[
                ('statutry_id', models.AutoField(primary_key=True, serialize=False)),
                ('epfo', models.CharField(blank=True, max_length=15, null=True)),
                ('epfo_date', models.DateField(blank=True, null=True)),
                ('esic', models.CharField(blank=True, max_length=15, null=True)),
                ('esic_date', models.DateField(blank=True, null=True)),
                ('gst', models.CharField(blank=True, max_length=15, null=True)),
                ('gst_date', models.DateField(blank=True, null=True)),
                ('shop_act', models.CharField(blank=True, max_length=15, null=True)),
                ('shop_act_date', models.DateField(blank=True, null=True)),
                ('labour', models.CharField(blank=True, max_length=15, null=True)),
                ('labour_from', models.DateField(blank=True, null=True)),
                ('labour_to', models.DateField(blank=True, null=True)),
                ('psara', models.CharField(blank=True, max_length=15, null=True)),
                ('psara_from', models.DateField(blank=True, null=True)),
                ('psara_to', models.DateField(blank=True, null=True)),
                ('factory', models.CharField(blank=True, max_length=15, null=True)),
                ('factory_from', models.DateField(blank=True, null=True)),
                ('factory_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.date.today)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(default=datetime.date.today)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, related_name='company_statutry_company', to='Sapp.company')),
            ],
            options={
                'db_table': 'sa_company_statury',
                'ordering': ['company'],
                'unique_together': {('company', 'epfo', 'esic', 'gst', 'shop_act', 'labour', 'psara')},
            },
        ),
    ]
