# Generated by Django 6.0.1 on 2026-02-08 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sapp', '0002_company_associateuser_license_useractivitylog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='associateuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='associateuser',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='associateuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='associateuser',
            name='suspension_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='associateuser',
            name='suspension_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='suspension_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='suspension_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='associateuser',
            name='companyid',
            field=models.ManyToManyField(blank=True, related_name='associate_company', to='Sapp.company'),
        ),
        migrations.CreateModel(
            name='SubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('operator', 'Operator'), ('employee', 'Employee')], default='employee', max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspension_end_time', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', models.TextField(blank=True, null=True)),
                ('associate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_users', to='Sapp.associateuser')),
                ('companyid', models.ManyToManyField(blank=True, related_name='subuser_company', to='Sapp.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subuser_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sub_users',
                'ordering': ['associate__associate_id', 'user__username'],
            },
        ),
    ]
