# Generated by Django 6.0.1 on 2026-02-15 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sapp', '0003_associateuser_address_associateuser_is_suspended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='associate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='Sapp.associateuser'),
        ),
        migrations.AddField(
            model_name='license',
            name='revoke_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='license',
            name='suspension_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
