# Generated by Django 6.0.1 on 2026-03-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sapp', '0004_license_associate_license_revoke_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_name',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
