# Generated by Django 6.0.1 on 2026-06-21 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sapp', '0005_alter_bank_name_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company_statury',
            name='created_at',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='company_statury',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company_statury',
            name='factory',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='company_statury',
            name='factory_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company_statury',
            name='factory_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company_statury',
            name='updated_at',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='company_statury',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
