# Generated by Django 6.0.7 on 2026-08-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sapp', '0007_company_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_logo',
        ),
        migrations.AddField(
            model_name='company',
            name='letterhead_background_pdf',
            field=models.FileField(blank=True, help_text='PDF of the letterhead artwork — required when letterhead_mode is overlay.', null=True, upload_to='letterheads/'),
        ),
        migrations.AddField(
            model_name='company',
            name='letterhead_bottom_margin_mm',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Blank bottom margin (mm) to match pre-printed stationery.', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='letterhead_mode',
            field=models.CharField(choices=[('drawn', 'Generated header/footer (no physical letterhead)'), ('preprinted', 'Pre-printed stationery (blank margins only)'), ('overlay', 'Digital letterhead overlay (background PDF)')], default='drawn', help_text="How PDFs handle this company's letterhead.", max_length=15),
        ),
        migrations.AddField(
            model_name='company',
            name='letterhead_top_margin_mm',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Blank top margin (mm) to match pre-printed stationery. Only used when letterhead_mode is preprinted/overlay.', null=True),
        ),
    ]
