# Generated by Django 6.0.7 on 2026-08-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sapp', '0008_remove_company_company_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
