# Generated by Django 6.0.7 on 2026-08-05 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sapp', '0006_company_created_at_company_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CxOwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, related_name='cx_owner', to='Sapp.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cx_owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Owner (Self-Signup)',
                'verbose_name_plural': 'Company Owners (Self-Signup)',
                'db_table': 'cx_owner_profile',
            },
        ),
        migrations.CreateModel(
            name='CxSubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('hr', 'HR'), ('front_desk', 'Front Desk'), ('operator', 'Operator'), ('employee', 'Employee'), ('recruitment', 'Recruitment')], max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_users', to='Cxapp.cxownerprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cx_sub_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sub User',
                'verbose_name_plural': 'Sub Users',
                'db_table': 'cx_sub_user',
            },
        ),
    ]
