# Generated by Django 6.0.7 on 2026-08-05 17:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cxapp', '0001_initial'),
        ('Sapp', '0006_company_created_at_company_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CxDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_name', models.CharField(max_length=255)),
                ('is_dailywage', models.BooleanField(default=False)),
                ('dailywage_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('basic_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('da', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=255)),
                ('updated_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, related_name='cx_designations', to='Sapp.company')),
            ],
            options={
                'verbose_name': 'Designation (Cxapp)',
                'verbose_name_plural': 'Designations (Cxapp)',
                'db_table': 'cx_designation',
                'ordering': ['designation_name'],
                'unique_together': {('designation_name', 'company')},
            },
        ),
        migrations.CreateModel(
            name='CxDesignationComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=100)),
                ('component_type', models.CharField(choices=[('allowance', 'Allowance'), ('deduction', 'Deduction')], max_length=10)),
                ('calculation_mode', models.CharField(choices=[('flat', 'Flat Amount'), ('percent_basic', '% of Basic Pay')], default='flat', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Flat ₹ value, or % value (e.g. 40.00 for 40%) depending on calculation_mode.', max_digits=10)),
                ('is_wage_code_excluded', models.BooleanField(default=True, help_text='True if this allowance is an "excluded component" under Wage Code Sec 2(y) (HRA, conveyance, etc). Leave True for nearly all allowances.')),
                ('is_taxable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='Cxapp.cxdesignation')),
            ],
            options={
                'verbose_name': 'Designation Component',
                'verbose_name_plural': 'Designation Components',
                'db_table': 'cx_designation_component',
                'ordering': ['display_order', 'component_name'],
                'unique_together': {('designation', 'component_name')},
            },
        ),
    ]
