# Generated by Django 6.0.7 on 2026-09-03 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyOwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default='Owner', help_text='Title shown in portal e.g. Managing Director', max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('can_view_employees', models.BooleanField(default=True)),
                ('can_view_attendance', models.BooleanField(default=True)),
                ('can_view_wages', models.BooleanField(default=True)),
                ('can_view_compliance', models.BooleanField(default=True)),
                ('can_view_reports', models.BooleanField(default=True)),
                ('can_download_pdf', models.BooleanField(default=True)),
                ('can_view_statutory', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, related_name='company_owners', to='Sapp.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_profiles_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Owner',
                'verbose_name_plural': 'Company Owners',
                'db_table': 'ca_company_owner_profile',
            },
        ),
    ]
