# Generated by Django 6.0.7 on 2026-07-20 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capp', '0002_alter_companyownerprofile_id'),
        ('Sapp', '0006_company_created_at_company_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyownerprofile',
            options={'verbose_name': 'Company Owner', 'verbose_name_plural': 'Company Owners'},
        ),
        migrations.RemoveField(
            model_name='companyownerprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='companyownerprofile',
            name='is_suspended',
        ),
        migrations.RemoveField(
            model_name='companyownerprofile',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='companyownerprofile',
            name='suspension_end_time',
        ),
        migrations.RemoveField(
            model_name='companyownerprofile',
            name='suspension_reason',
        ),
        migrations.AddField(
            model_name='companyownerprofile',
            name='can_download_pdf',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyownerprofile',
            name='can_view_attendance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyownerprofile',
            name='can_view_compliance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyownerprofile',
            name='can_view_employees',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyownerprofile',
            name='can_view_reports',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyownerprofile',
            name='can_view_statutory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyownerprofile',
            name='can_view_wages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyownerprofile',
            name='designation',
            field=models.CharField(default='Owner', help_text='Title shown in portal e.g. Managing Director', max_length=100),
        ),
        migrations.AddField(
            model_name='companyownerprofile',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyownerprofile',
            name='company',
            field=models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, related_name='company_owners', to='Sapp.company'),
        ),
        migrations.AlterField(
            model_name='companyownerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='companyownerprofile',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_profiles_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companyownerprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='companyownerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='companyownerprofile',
            table='company_owner_profile',
        ),
    ]
